# Generated by Django 2.2.4 on 2022-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carchive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='prod_date',
            field=models.DateField(default=''),
        ),
    ]
